import React, { createContext, useReducer } from 'react';

const initialState = [
	{
		active: true,
		audible: false,
		autoDiscardable: true,
		discarded: false,
		favIconUrl: 'https://www.jd.com/favicon.ico',
		groupId: -1,
		height: 777,
		highlighted: true,
		id: 1559,
		incognito: false,
		index: 6,
		mutedInfo: {
			muted: false,
		},
		pinned: false,
		selected: true,
		status: 'complete',
		title: '京东(JD.COM)-正品低价、品质保障、配送及时、轻松购物！',
		url: 'https://www.jd.com/',
		width: 1512,
		windowId: 26,
		action: 'start',
		indexNum: 0,
		date: 1656672880677,
		userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
		isMobile: false,
		hasTouch: false,
		deviceScaleFactor: 2,
		type: 'start',
	},
	{
		x: 423,
		y: 58,
		url: 'https://www.jd.com/',
		date: 1656672881928,
		height: 32,
		xpath: '//*[@id="key"]',
		width: 488,
		value: '',
		pageX: 747,
		pageY: 74,
		clientX: 747,
		clientY: 74,
		selector: 'html > body > div > div > div > div > div > div > input',
		iframe: '',
		indexNum: 1,
		innerHtml: '',
		localName: 'input',
		localNameType: 'text',
		type: 'click',
	},
	{
		x: 423,
		y: 58,
		url: 'https://www.jd.com/',
		date: 1656672885903,
		height: 32,
		xpath: '//*[@id="key"]',
		width: 488,
		value: '手机',
		pageX: 747,
		pageY: 74,
		clientX: 747,
		clientY: 74,
		selector: 'html > body > div > div > div > div > div > div > input',
		iframe: '',
		indexNum: 2,
		innerHtml: '',
		localName: 'input',
		localNameType: 'text',
		type: 'change',
	},
	{
		userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
		isMobile: false,
		hasTouch: false,
		deviceScaleFactor: 2,
		type: 'start',
		active: true,
		audible: false,
		autoDiscardable: true,
		discarded: false,
		groupId: -1,
		height: 777,
		highlighted: true,
		id: 1559,
		incognito: false,
		index: 6,
		mutedInfo: {
			muted: false,
		},
		pinned: false,
		selected: true,
		status: 'complete',
		title: '手机 - 商品搜索 - 京东',
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&enc=utf-8&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b',
		width: 1512,
		windowId: 26,
		action: 'replacePage',
		indexNum: 3,
		date: 1656672887803,
	},
	{
		x: 1395,
		y: 526,
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&enc=utf-8&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b',
		date: 1656672894577,
		height: 25,
		xpath: '//*[@id="J_topPage"]/a[2]',
		width: 48,
		pageX: 1415,
		pageY: 529,
		clientX: 1415,
		clientY: 529,
		selector: 'html > body > div > div > div > div > div > div > div > div > a',
		iframe: '',
		indexNum: 4,
		innerHtml: '>',
		localName: 'a',
		localNameType: '',
		type: 'click',
	},
	{
		userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
		isMobile: false,
		hasTouch: false,
		deviceScaleFactor: 2,
		type: 'start',
		active: true,
		audible: false,
		autoDiscardable: true,
		discarded: false,
		favIconUrl: 'https://search.jd.com/favicon.ico',
		groupId: -1,
		height: 777,
		highlighted: true,
		id: 1559,
		incognito: false,
		index: 6,
		mutedInfo: {
			muted: false,
		},
		pinned: false,
		selected: true,
		status: 'complete',
		title: '手机 - 商品搜索 - 京东',
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b&page=3&s=57&click=0',
		width: 1512,
		windowId: 26,
		action: 'replacePage',
		indexNum: 5,
		date: 1656672894586,
	},
	{
		editable: false,
		frameId: 0,
		menuItemId: '["include","5000+"]',
		pageUrl:
			'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b&page=3&s=57&click=0',
		selectionText: '5000+',
		type: 'assert',
		xpath: '//*[@id="J_resCount"]',
		selector: 'html > body > div > div > div > div > div > div > div > div > span',
		iframe: '',
		pageX: 1233,
		pageY: 539,
		clientX: 1233,
		clientY: 539,
		localName: 'span',
		x: 1222.421875,
		y: 531,
		assertions: {
			value: '5000+',
			action: 'include',
		},
		innerHtml: '5000+',
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b&page=3&s=57&click=0',
		indexNum: 6,
		date: 1656672904218,
	},
	{
		x: 314,
		y: 526,
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b&page=3&s=57&click=0',
		date: 1656672908814,
		height: 25,
		xpath: '//*[@id="J_filter"]/div[1]/div[1]/a[2]',
		width: 56,
		pageX: 348,
		pageY: 532,
		clientX: 348,
		clientY: 532,
		selector: 'html > body > div > div > div > div > div > div > div > div > a',
		iframe: '',
		indexNum: 7,
		innerHtml: '销量',
		localName: 'a',
		localNameType: '',
		type: 'click',
	},
	{
		userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
		isMobile: false,
		hasTouch: false,
		deviceScaleFactor: 2,
		type: 'start',
		active: true,
		audible: false,
		autoDiscardable: true,
		discarded: false,
		favIconUrl: 'https://search.jd.com/favicon.ico',
		groupId: -1,
		height: 777,
		highlighted: true,
		id: 1559,
		incognito: false,
		index: 6,
		mutedInfo: {
			muted: false,
		},
		pinned: false,
		selected: true,
		status: 'complete',
		title: '手机 - 商品搜索 - 京东',
		url: 'https://search.jd.com/Search?keyword=%E6%89%8B%E6%9C%BA&wq=%E6%89%8B%E6%9C%BA&pvid=8c8dddca3ba94d9886c1a85a1edc571b&psort=3&click=1',
		width: 1512,
		windowId: 26,
		action: 'replacePage',
		indexNum: 8,
		date: 1656672908826,
	},
];

const reducer = (state, action) => {
	switch (action) {
		case 'push':
			return [...initialState, state];
		case 'replace':
			return initialState.map((it) => (it.date === state.date ? it : { ...it, ...state }));
		case 'delete':
			return initialState.filter((it) => it.date !== state.date);
		case 'pop':
			initialState.length = initialState.length - 1;
			return initialState;
		case 'clear':
			return [];
	}
};

export const ContainerContext = createContext({});

export const UseRedux = (props) => {
	const [dataSoure, dispatch] = useReducer(reducer, initialState);
	return <ContainerContext.Provider value={{ dataSoure, dispatch }}>{props.children}</ContainerContext.Provider>;
};
